version: '3'

services:
  flask:
    build: ./
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes: 
      - ./:/app
    env_file: .env

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
